
const CACHE="arabic-journey-791566f7b63c";const ASSETS=["./","./index.html","./manifest.webmanifest","./css/app.css","./css/responsive.css","./js/app.js","./js/arabic-utils.js","./js/auth-retry.js","./js/backup.js","./js/config.js","./js/dashboard-activity.js","./js/i18n.js","./js/learning-settings.js","./js/learning-ui.js","./js/login.js","./js/morphology.js","./js/notifications.js","./js/onboarding.js","./js/progress.js","./js/pwa.js","./js/quiz.js","./js/review.js","./js/router.js","./js/settings.js","./js/srs-data.js","./js/srs-details.js","./js/srs-settings.js","./js/srs.js","./js/statistics.js","./js/storage.js","./js/supabase.js","./js/sync.js","./js/ui.js","./js/vocabulary-data.js","./js/vocabulary.js","./js/word-navigation.js","./js/pages/dashboard.js","./js/pages/future.js","./fonts/Lateef-Regular.ttf","./fonts/NotoSansBengali.ttf","./icons/app.svg","./icons/icon-192.png","./icons/icon-512.png","./vendor/supabase.js"];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS.map(asset=>new Request(new URL(asset,self.registration.scope),{cache:'reload'})))).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(Promise.all([caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('arabic-journey-')&&k!==CACHE).map(k=>caches.delete(k)))),self.clients.claim()])));
self.addEventListener('message',event=>{if(event.data?.type==='APPLY_UPDATE')self.skipWaiting();});
// Only application assets enter this shared cache. Authenticated API data stays in per-user IndexedDB.
self.addEventListener('fetch',event=>{const url=new URL(event.request.url),scope=new URL(self.registration.scope);if(event.request.method!=='GET'||url.origin!==scope.origin||!url.pathname.startsWith(scope.pathname))return;const relative='./'+url.pathname.slice(scope.pathname.length);if(!ASSETS.includes(relative)&&event.request.mode!=='navigate')return;event.respondWith(event.request.mode==='navigate'?caches.match(new URL('./index.html',scope)).then(cached=>cached||fetch(event.request)):caches.match(event.request).then(cached=>cached||fetch(event.request)));});
self.addEventListener('sync',event=>{if(event.tag==='arabic-journey-sync')event.waitUntil(self.clients.matchAll({type:'window'}).then(clients=>clients.forEach(client=>client.postMessage({type:'sync'}))));});
self.addEventListener('push',event=>{let data={};try{data=event.data?.json()||{};}catch{}event.waitUntil(self.registration.showNotification(data.title||'Arabic Revision Time 📚',{body:data.body||'Your vocabulary is ready for review.',icon:'./icons/icon-192.png',badge:'./icons/icon-192.png',tag:'arabic-journey-reminder',data:{url:self.registration.scope+'index.html#/review'}}));});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(async clients=>{const url=self.registration.scope+'index.html#/review';const existing=clients.find(client=>client.url.startsWith(self.registration.scope));if(existing){await existing.navigate(url);return existing.focus();}return self.clients.openWindow(url);}));});
