import test from 'node:test';import assert from 'node:assert/strict';import {PGlite}from'@electric-sql/pglite';import {readFile,readdir}from'node:fs/promises';import {randomUUID}from'node:crypto';
test('Early batches are owner-scoped and ordered; saving them updates only selected future words',async()=>{
 const db=new PGlite(),alice=randomUUID(),bob=randomUUID(),ids=[randomUUID(),randomUUID(),randomUUID()];
 try{await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);for(const f of(await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile('supabase/migrations/'+f,'utf8'));await db.query('insert into auth.users(id)values($1),($2)',[alice,bob]);await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${alice}',false)`);
 for(const [i,id]of ids.entries())await db.query("select public.vocabulary_write($1,'save',$2,null,$3)",[randomUUID(),id,JSON.stringify({arabic_word:'كِتَابٌ'+i,bangla_meaning:'বই',english_meaning:'book'})]);
 await db.exec('reset role');for(const [i,id]of ids.entries())await db.query("update public.word_review_state set next_review_at=now()+($1||' days')::interval where word_id=$2",[[-1,1,2][i],id]);await db.exec('set role authenticated');
 const state=async id=>(await db.query('select *from public.word_review_state where word_id=$1',[id])).rows[0];const dueBefore=await state(ids[0]),laterBefore=await state(ids[2]);const batch=(await db.query('select public.fixed_upcoming(1)result')).rows[0].result;assert.equal(batch.total,2);assert.deepEqual(batch.words.map(w=>w.id),[ids[1]]);
 const args=[randomUUID(),ids[1],batch.words[0].state.revision,'good'];const saved=(await db.query("select public.fixed_review($1,$2,$3,$4,1000,'recorded_practice')result",args)).rows[0].result;assert.equal(saved.state.review_count,1);assert.equal(saved.state.stage,1);assert.deepEqual(await state(ids[0]),dueBefore);assert.deepEqual(await state(ids[2]),laterBefore);assert.equal((await db.query('select public.fixed_due()result')).rows[0].result.total,1);assert.deepEqual((await db.query("select public.fixed_review($1,$2,$3,$4,1000,'recorded_practice')result",args)).rows[0].result,saved);
 const cfg=(await db.query('select *from public.user_settings')).rows[0];const goals={...cfg.daily_goals,allow_early_reviews:true,review_batch_size:20};await db.query('select public.save_learning_settings($1,$2,$3,$4,$5)',[cfg.revision,JSON.stringify(cfg.quiz_options),JSON.stringify(cfg.mastery_thresholds),JSON.stringify(cfg.weak_weights),JSON.stringify(goals)]);assert.equal((await db.query('select daily_goals from public.user_settings')).rows[0].daily_goals.review_batch_size,20);
 await db.exec(`select set_config('request.jwt.claim.sub','${bob}',false)`);assert.equal((await db.query('select public.fixed_upcoming()result')).rows[0].result.total,0);
 }finally{await db.close();}
});
