
begin;
create function public.learning_statistics()returns jsonb language sql stable security invoker set search_path='' as $$
 with cfg as(select *, (statement_timestamp() at time zone timezone)::date today from public.user_settings where user_id=auth.uid()), words as(select w.*,(w.created_at at time zone cfg.timezone)::date as study_day from public.words w cross join cfg where w.user_id=auth.uid() and w.deleted_at is null), reviews as(select h.*,(h.occurred_at at time zone cfg.timezone)::date as study_day from public.review_history h cross join cfg where h.user_id=auth.uid()), answers as(select a.*,(a.created_at at time zone cfg.timezone)::date as study_day from public.quiz_answers a cross join cfg where a.user_id=auth.uid()), word_events as(select(w.created_at at time zone cfg.timezone)::date as study_day from public.words w cross join cfg where w.user_id=auth.uid()),activity as(select study_day,count(*) n from(select study_day from word_events union all select study_day from reviews union all select study_day from answers)a group by study_day),states as(select r.* from public.word_review_state r join words w on w.id=r.word_id where r.user_id=auth.uid() and r.algorithm='fixed' and r.deleted_at is null)
 select jsonb_build_object('today',cfg.today,'timezone',cfg.timezone,'total',(select count(*)from words),'week',(select count(*)from words where study_day>=cfg.today-6),'month',(select count(*)from words where date_trunc('month',study_day)=date_trunc('month',cfg.today)), 'new_today',(select count(*)from words where study_day=cfg.today),'reviewed_today',(select count(*)from reviews where study_day=cfg.today),'total_reviews',(select count(*)from reviews),'due',(select count(*)from states where next_review_at<=statement_timestamp()),'learning',(select count(*)from states where mastery_status in('new','learning')),'reviewing',(select count(*)from states where mastery_status='reviewing'),'mastered',(select count(*)from states where mastery_status='mastered'),'weak',(select count(*)from states where weak_score>=(cfg.weak_weights->>'threshold')::numeric),'weak_due',(select count(*)from states where weak_score>=(cfg.weak_weights->>'threshold')::numeric and next_review_at<=statement_timestamp()),'favorites',(select count(*)from words where favorite),'quiz_today',(select count(*)from answers where study_day=cfg.today),'quiz_accuracy',(select round(100.0*count(*)filter(where correct)/nullif(count(*),0),1)from answers),'accuracy',(select round(100.0*count(*)filter(where rating<>'again')/nullif(count(*),0),1)from reviews),'accuracy7',(select round(100.0*count(*)filter(where rating<>'again')/nullif(count(*),0),1)from reviews where study_day>=cfg.today-6),'accuracy30',(select round(100.0*count(*)filter(where rating<>'again')/nullif(count(*),0),1)from reviews where study_day>=cfg.today-29),'calendar',coalesce((select jsonb_agg(to_jsonb(a)order by study_day)from activity a),'[]'),'goals',cfg.daily_goals)from cfg;
$$;
create function public.learning_history(p_from date default null,p_to date default null,p_page integer default 0)returns jsonb language sql stable security invoker set search_path='' as $$
 with cfg as(select timezone from public.user_settings where user_id=auth.uid()), events as(select h.id,h.word_id,w.arabic_word,h.occurred_at as event_at,h.rating result,h.prior_interval,h.new_interval,h.next_review_at,'review' kind from public.review_history h join public.words w on w.id=h.word_id and w.user_id=h.user_id where h.user_id=auth.uid() union all select a.id,a.word_id,w.arabic_word,a.created_at,case when a.correct then 'correct'else 'incorrect'end,null,null,null,'quiz'from public.quiz_answers a join public.words w on w.id=a.word_id and w.user_id=a.user_id where a.user_id=auth.uid()),filtered as(select *from events cross join cfg where(p_from is null or(event_at at time zone timezone)::date>=p_from)and(p_to is null or(event_at at time zone timezone)::date<=p_to)),selected as(select *from filtered order by event_at desc,id limit 25 offset greatest(0,p_page)*25)
 select jsonb_build_object('total',(select count(*)from filtered),'events',coalesce((select jsonb_agg(to_jsonb(selected))from selected),'[]'));
$$;
revoke all on function public.learning_statistics(),public.learning_history(date,date,integer)from public,anon;grant execute on function public.learning_statistics(),public.learning_history(date,date,integer)to authenticated;
commit;
