begin;
do $patch$ declare definition text;begin
select pg_get_functiondef('public.vocabulary_list(text,text,text,uuid,boolean,date,date,integer,text,boolean,boolean,boolean)'::regprocedure)into definition;
if position('and (coalesce(p_status' in definition)=0 then raise exception 'Expected vocabulary filter missing';end if;
definition:=replace(definition,'and (coalesce(p_status', 'and ((p_status in (''learning'',''reviewing'') and exists(select 1 from public.word_review_state state where state.word_id=w.id and state.user_id=w.user_id and state.algorithm=''fixed'' and state.deleted_at is null and (case when p_status=''learning'' then state.mastery_status in (''new'',''learning'') else state.mastery_status=''reviewing'' end))) or (p_status=''today'' and (w.created_at at time zone (select timezone from public.user_settings where user_id=auth.uid()))::date=(now()at time zone (select timezone from public.user_settings where user_id=auth.uid()))::date) or coalesce(p_status');
execute definition;end$patch$;
create function public.activity_history(p_from date default null,p_to date default null,p_page integer default 0,p_kind text default null)returns jsonb language sql stable security invoker set search_path='' as $$
 with cfg as(select timezone from public.user_settings where user_id=auth.uid()), events as(select h.id,h.word_id,w.arabic_word,h.occurred_at as event_at,h.rating result,h.prior_interval,h.new_interval,h.next_review_at,'review' kind from public.review_history h join public.words w on w.id=h.word_id and w.user_id=h.user_id where h.user_id=auth.uid() union all select a.id,a.word_id,w.arabic_word,a.created_at,case when a.correct then 'correct'else 'incorrect'end,null,null,null,'quiz'from public.quiz_answers a join public.words w on w.id=a.word_id and w.user_id=a.user_id where a.user_id=auth.uid() union all select w.id,w.id,w.arabic_word,w.created_at,'added',null::integer,null::integer,null::timestamptz,'word'from public.words w where w.user_id=auth.uid()),filtered as(select *from events cross join cfg where(p_kind is null or kind=p_kind)and(p_from is null or(event_at at time zone timezone)::date>=p_from)and(p_to is null or(event_at at time zone timezone)::date<=p_to)),selected as(select *from filtered order by event_at desc,id limit 25 offset greatest(0,p_page)*25)
 select jsonb_build_object('total',(select count(*)from filtered),'events',coalesce((select jsonb_agg(to_jsonb(selected))from selected),'[]'));
$$;
revoke all on function public.activity_history(date,date,integer,text)from public,anon;grant execute on function public.activity_history(date,date,integer,text)to authenticated;
commit;
